name: yamllint

on:
  pull_request:
    branches:
      - master

jobs:
  build-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Yaml Lint
      uses: ibiqlik/action-yamllint@v0.0.2
      with:
        file_or_dir: src/*.yaml
        strict: true