name: main

on:
  pull_request:
    branches:
      - master

jobs:
  build-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Yaml Lint
      uses: ibiqlik/action-yamllint@v0.0.2
      with:
        file_or_dir: src/*.yaml
        strict: true
    - name: Generate markdown and json
      uses: awesome-global-contributions/action-yq@v0.1.2
      with:
        file: bin/yaml2markdown.sh
    - name: Add new commit
      uses: zwaldowski/git-commit-action@v1
      with:
        commit_message: "chore: yaml2markdown.sh"
    - name: Push new commit
      run: git push https://${{ GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}.git
